apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: chainwise-psp
  namespace: chainwise
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1000
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1000
        max: 65535
  seLinux:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainwise-psp-user
  namespace: chainwise
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chainwise-psp-role
  namespace: chainwise
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['chainwise-psp']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chainwise-psp-rolebinding
  namespace: chainwise
roleRef:
  kind: Role
  name: chainwise-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: chainwise-psp-user
  namespace: chainwise
- kind: ServiceAccount
  name: chainwise-service-account
  namespace: chainwise