apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainwise-service-account
  namespace: chainwise
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: chainwise
  name: chainwise-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chainwise-role-binding
  namespace: chainwise
subjects:
- kind: ServiceAccount
  name: chainwise-service-account
  namespace: chainwise
roleRef:
  kind: Role
  name: chainwise-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainwise-monitoring
  namespace: chainwise
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chainwise-monitoring-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chainwise-monitoring-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chainwise-monitoring-cluster-role
subjects:
- kind: ServiceAccount
  name: chainwise-monitoring
  namespace: chainwise